language: go
sudo: required

go:
  - "1.14"

services:
  - docker

before_install:
  - docker pull vicanso/etcd 
  - docker run -p 2379:2379 -d vicanso/etcd etcd --listen-client-urls 'http://0.0.0.0:2379' --advertise-client-urls 'http://0.0.0.0:2379'

script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - make lint
  - make test

after_success:
  - docker build -t pike .
  - export VERSION=`cat assets/version`
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag pike $DOCKER_USERNAME/pike:$VERSION
  - docker tag pike $DOCKER_USERNAME/pike:latest
  - docker push $DOCKER_USERNAME/pike:$VERSION
  - docker push $DOCKER_USERNAME/pike:latest
  - docker images